#!/usr/bin/env bash
# It displays numbers from 1 to 100 in list format.
#   displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   displays "Fizz" when the number is a multiple of 3.
#   displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

for digit in {1..100}
do
  if (( digit % 3 == 0 && digit % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( digit % 3 == 0 ))
  then
    echo "Fizz"
  elif (( digit % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$digit"
  fi
done
