#!\usr\bin\env bash
# scipt that configures an Ubuntu server:
#  localhost resolves to 127.0.0.2
#  facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/host.new
echo "127.0.0.2 	localhost" >~/host.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f /host.new /etc/hosts
